GoodLyf/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
                       url(r'^$', 'GoodLyf.views.home', name='home'),
                       url(r'^chaining/', include('smart_selects.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^goodlyf/', include('goodlyf.urls')),

                       )
if settings.DEBUG:
    urlpatterns += patterns(
        'django.views.static',
        (r'^media/(?P<path>.*)',
        'serve',
        {'document_root': settings.MEDIA_ROOT}), )

admin.site.site_header = settings.ADMIN_SITE_HEADER

goodlyf/urls.py
__author__ = 'root'
from django.conf.urls import url, patterns
from goodlyf.views import *

urlpatterns = patterns('',
                       url(r'^register/$', register, name='register'),
                       url(r'^login/$', user_login, name='login'),
                       url(r'^logout/$', user_logout, name='logout'),
                       url(r'^create_staff', create_staff, name='create_staff'),
                       url(r'^create_handyman', create_handyman, name='create_handyman'),
                       url(r'^booking', booking, name='booking'),
                       url(r'^incoming-jobs/$', incoming_jobs, name='incoming_jobs'),
                       url(r'^cancelled-jobs/$', cancelled_order, name='cancelled_jobs'),
                       url(r'^(?P<job_id>\d+)/$', job, name='job'),
                       url(r'^assign/(?P<order_id>\d+)/$', assign, name='assign'),
                       url(r'^worker-details/(?P<worker_id>\d+)/$', worker_details, name='worker_details'),
                       url(r'^my-jobs/$', my_jobs, name='my_jobs'),
                       url(r'^dashboard/$', dashboard, name='dashboard'),
                       url(r'^thank-you/$', thank_you, name='thank_you'),
                       url(r'^workers-profile/$', worker_profile, name='worker_profile'),
                       url(r'^complete-jobs/$', complete_jobs, name='complete_jobs'),
                       url(r'^edit/(?P<job_id>\d+)/$', edit_job, name='edit_job'),
                       url(r'^push-to-admin/(?P<job_id>\d+)/$', cancelled_job, name='cancelled_job'),
                       url(r'^client/(?P<order_id>\d+)/$', client, name='client'),
                       url(r'^delete/(?P<job_id>\d+)/$', complete_job_delete, name='complete_job_delete'),
                       url(r'^search/$', search_worker, name='search'),
                       )

goodlyf/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import User
from datetime import datetime
from django.core.validators import RegexValidator
from smart_selects.db_fields import ChainedForeignKey
from extended_choices import Choices



class WorkerCategory(models.Model):
    category_name = models.CharField(max_length=40, unique=True, blank=False)

    def __str__(self):
        return self.category_name


class Worker(models.Model):

    user = models.OneToOneField(User,)
    worker_category = models.ForeignKey(WorkerCategory,)
    phone_number = PhoneNumberField(unique=True)
    national_id = models.PositiveIntegerField(max_length=10, unique=True, blank=False)
    year_of_birth = models.DateField(unique=False, default='1975-01-01')
    profile_image = models.ImageField(verbose_name='Avatar', )

    def __str__(self):
        return self.user.username


class NextOfKinRelation(models.Model):
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    name = models.CharField(max_length=50, blank=False, validators=[alpha_validator])

    def __str__(self):
        return self.name


class WorkerNextOfKin(models.Model):
    worker = models.OneToOneField(Worker, unique=True)

    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')

    first_name = models.CharField(max_length=40, blank=False, validators=[alpha_validator])
    last_name = models.CharField(max_length=40, blank=False, validators=[alpha_validator])
    relationship = models.ForeignKey(NextOfKinRelation)
    phone_number = PhoneNumberField(unique=True)
    email = models.EmailField(unique=True, blank=True)


class WorkerResidence(models.Model):
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    country = models.CharField(max_length=25, blank=False, default='Kenya', validators=[alpha_validator])
    county = models.CharField(max_length=25,  blank=False, validators=[alpha_validator])
    sub_county = models.CharField(max_length=25,  blank=False, validators=[alpha_validator])
    location = models.CharField(max_length=25, blank=False, verbose_name='Street', validators=[alpha_validator])
    village = models.CharField(max_length=25, blank=False, verbose_name='Physical location', validators=[alpha_validator])
    worker = models.OneToOneField(Worker, unique=True)

    def __str__(self):
        return self.county


class Skill(models.Model):
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    name = models.CharField(max_length=100, blank=False, unique=True, validators=[alpha_validator])

    def __str__(self):
        return self.name


class WorkerSkill(models.Model):
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    worker = models.OneToOneField(Worker, unique=True)
    skill = models.ForeignKey(Skill)
    extra_skill = models.CharField(max_length=30, unique=False, blank=True, validators=[alpha_validator])


class ServiceCategory(models.Model):

    category_name = models.CharField(max_length=40, unique=True, blank=False, verbose_name='Services')

    def __str__(self):
        return self.category_name


class ServiceDuration(models.Model):
    """ half a day or full day """
    duration = models.CharField(max_length=50, blank=False, unique=True, default='Half Day', )

    def __str__(self):
        return self.duration


class ServicePricing(models.Model):
    price = models.CharField(max_length=5, unique=True, blank=False, default='1000')

    def __str__(self):
        return self.price


class Service(models.Model):
    service_category = models.ForeignKey(ServiceCategory)
    name = models.CharField(max_length=200, blank=False, )

    def __str__(self):
        return self.name


class IncomingJob(models.Model):
    STATES = Choices(
        ('NOT_SEEN', 0, 'Not Seen'),
        ('SEEN', 1, 'Seen')
    )
    ASSIGNMENT = Choices(
        ('NOT_ASSIGNED', 0, 'Not Assigned'),
        ('Assigned', 1, 'Assigned')
    )
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    service_category = models.ForeignKey(ServiceCategory)
    service_name = ChainedForeignKey(
        Service,
        chained_field="service_category",
        chained_model_field="service_category",
        auto_choose=True,
        show_all=False
    )

    date_posted = models.DateTimeField(auto_now_add=True, verbose_name='Received On')
    date_job_starts = models.DateField(verbose_name='Starts On', default=datetime.now)
    state = models.SmallIntegerField(choices=STATES, default=STATES.NOT_SEEN)
    assignment = models.SmallIntegerField(choices=ASSIGNMENT, default=ASSIGNMENT.NOT_ASSIGNED)
    time_remaining = models.PositiveIntegerField(default=0, blank=True)

    class Meta:
        ordering = ['-date_posted']

    def __str__(self):
        return self.service_category.category_name


class JobAssignment(models.Model):
    PUSH_STATES = Choices(
        ('NOT_PUSHED', 0, 'Not pushed'),
        ('PUSHED', 1, 'Pushed')
    )
    STATES = Choices(
        ('PENDING', 0, 'Pending'),
        ('IN PROGRESS', 1, 'In Progress'),
        ('COMPLETE', 2, 'complete'),
        ('CANCELLED', 3, 'Cancelled'),
    )

    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    job = models.ForeignKey(IncomingJob)
    assigned_to = models.ForeignKey(Worker)
    date_job_ends = models.DateField(verbose_name='Ends On')
    state = models.SmallIntegerField(choices=STATES, default=STATES.PENDING)
    push_state = models.SmallIntegerField(choices=PUSH_STATES, default=PUSH_STATES.NOT_PUSHED)

    def __str__(self):
        return self.job.service_category.category_name

    class Meta:
        ordering = ['-assigned_to']


class FeedbackCategory(models.Model):
    category_name = models.CharField(max_length=50, blank=False, unique=True, )

    def __str__(self):
        return self.category_name


class ServiceMenu(models.Model):
    category = models.ForeignKey(ServiceCategory)
    name = models.OneToOneField(Service)
    time = models.ForeignKey(ServiceDuration)
    price = models.ForeignKey(ServicePricing)

    def __str__(self):
        return self.name.name


class SupervisorAssignment(models.Model):
    supervisor = models.ForeignKey(Worker)
    handyman = models.OneToOneField(User,)

    def __str__(self):
        return self.handyman.username


class JobFeedback(models.Model):

    job = models.ForeignKey(JobAssignment)
    comment = models.CharField(max_length=2500, blank=True)
    date_posted = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.job.job.service_name


class Client(models.Model):
    job = models.ForeignKey(IncomingJob)
    name = models.CharField(max_length=30, unique=False, blank=False, )
    email = models.EmailField(blank=True)
    phone_number = PhoneNumberField(unique=False)
    area = models.CharField(max_length=30, unique=False, blank=False)
    street = models.CharField(max_length=30, unique=False, blank=False)
    estate = models.CharField(max_length=30, unique=False, blank=False)
    house_number = models.IntegerField(blank=True, default=None, null=True)

    def __str__(self):
        return self.name


class Feedback(models.Model):
    alpha_validator = RegexValidator(r'^[a-zA-Z]', 'Only alphabetic characters are allowed.')
    reviewed_job = models.ForeignKey(IncomingJob)
    client = models.ForeignKey(Client)
    title = models.ForeignKey(FeedbackCategory)
    text = models.CharField(max_length=1000, blank=False, validators=[alpha_validator])

GoodLyf/views.py
__author__ = 'steven'
from django.shortcuts import render
from goodlyf.models import ServiceCategory, ServiceMenu

def home(request):
    service_categories = ServiceCategory.objects.all()[:4]
    service_categories_next = ServiceCategory.objects.all()[5:9]
    service_categories_last = ServiceCategory.objects.all()[10:11]

    cleaning_services = ServiceMenu.objects.filter(category_id=1)
    gardening_services = ServiceMenu.objects.filter(category_id=9)
    handyman_services = ServiceMenu.objects.filter(category_id=11)
    installation_services = ServiceMenu.objects.filter(category_id=3)
    painting_services = ServiceMenu.objects.filter(category_id=10)
    petcare_services = ServiceMenu.objects.filter(category_id=4)
    plumbing_services = ServiceMenu.objects.filter(category_id=6)
    transport_services = ServiceMenu.objects.filter(category_id=5)

    return render(request, 'index.html', {'service_categories': service_categories,
                                          'service_categories_next': service_categories_next,
                                          'service_categories_last': service_categories_last,
                                          'cleaning_services': cleaning_services,
                                          'gardening_services': gardening_services,
                                          'handyman_services': handyman_services,
                                          'installation_services': installation_services,
                                          'painting_services': painting_services,
                                          'petcare_services': petcare_services,
                                          'plumbing_services': plumbing_services,
                                          'transport_services': transport_services,
                                          })

templates/goodlyf/booking.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12">
           <span class="pull-left h4 text-success">
               <img src="{% static 'images/goodlyf1.png' %}" alt="pic-cleaning" height="33" width="250" />
           </span>
           <a href="{% url 'home' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a>
            &nbsp;&nbsp;|&nbsp;&nbsp;
           <i class="glyphicon glyphicon-phone"></i>&nbsp;&nbsp;+254 724 230 064
           <a href="{% url 'login' %}" class="pull-right">login</a>
        </div>
    </div>
</div>
</nav>

<div class="container booking-accordion">
    <div class="row">
        <div class="col-sm-12 row-centered ">
            <div class="text-info">
            {% if messages  %}
            {% for message in messages %}
            <ul class="text-warning">{% if message.tags %}{% endif %}&nbsp;&nbsp;&nbsp; {{ message }}</ul>
            {% endfor %}
            {% endif %}
            </div>
                        <!--accordion-->
            <div class="panel-group accordion-group " id="accordion" role="tablist" aria-multiselectable="true">
                  <div class="panel panel-default ">
                      <!--panel heading for step one.-->
                    <div class="panel-heading" role="tab" id="headingOne">
                      <h4 class="panel-title ">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                         <h5 class="btn btn-lg pricing-td" style="width: 100%">Choose a service</h5>
                        </a>
                      </h4>
                    </div>
                      <!--end panel heading for step one-->

                    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
                      <!--step 1 body-->
                        <div class="panel-body">

                          {% if job_form.errors %}
                                <div class="text-danger">Please correct the error{{ job_form.errors|pluralize }} below.</div>
                          {% endif %}


          <form  class="form-horizontal upload-form" role="form"  id="booking" method="post" action="/goodlyf/booking/" enctype="multipart/form-data">

              {% csrf_token %}
              <div class="row">
                  <div class="col-sm-6">

                <div class="fieldWrapper">
                    {{ job_form.service_category.label_tag}}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ job_form.service_category }}
                </div>
                      </div>
                  <div class="col-sm-6">
                <div class="fieldWrapper">
                    {{ job_form.service_name.label_tag}}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ job_form.service_name }}
                </div>
                  </div>
              </div>
           </div>
        </div>


                <!--end step 1 body-->

                      <!--step 2 heading -->
                  <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingTwo">
                      <h4 class="panel-title">
                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                          <h5 class="btn btn-lg pricing-td" style="width: 100%">When do you want us to start the job?</h5>
                        </a>
                      </h4>
                    </div>
                      <!--end step 2 heading-->

                    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                        <!--step 2 body-->
                      <div class="panel-body">


                <div class="fieldWrapper">
                    {{ job_form.date_job_starts.errors }}
                    {{ job_form.date_job_starts.label_tag}}

                    &nbsp;&nbsp;&nbsp;&nbsp;
                    <input type="date" name="date_job_starts" required="required" placeholder="mm/dd/yyyy">
                </div>

                          <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-info" type="submit" class="btn btn-default">Submit</button>
                                </div>
                          </div>
                      </form>
                    </div>
                  </div>
                </div>

            </div>

            </div>
            </div>
            </div></div>

<div class="container navbar-fixed-bottom">
     <hr>
    <div class="row footer">
        &copy steven kyalo 2015
    </div>
</div>

{% endblock content %}

templates/goodlyf/cancelled-jobs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12">
           <span class="pull-left h4 text-success">
               <img src="{% static 'images/goodlyf1.png' %}" alt="pic-cleaning" height="33" width="250" />
           </span>
           <a href="{% url 'home' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a>
            {% if user.is_authenticated %}
            <span></span>
            {% else %}
            &nbsp;&nbsp;|&nbsp;&nbsp;
           <a href="{% url 'booking' %}" class="btn btn-primary" title="Book now!">Book online</a>
            {% endif %}

           {% if user.is_authenticated %}
            <span class="text-success pull-right">
               <i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp; {{ user.username|capfirst }}&nbsp;&nbsp;

            <a href="{% url 'logout' %}">logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="pull-right">login</a>

            </span>
            {% endif %}
        </div>
    </div>
</div>
</nav>
<div class="container">
    <div class="row">
        {% for order in orders %}
        <ul>&nbsp;&nbsp;&nbsp;
        </ul>
        {% endfor %}
    </div>
    <div class="col-sm-12 ">
            <h5 class="btn btn-lg pricing-td" style="width: 100%">Cancelled</h5>
            <h4></h4>
            {% if orders %}
            <table class="table table-striped table-bordered">
                <thead>
                <tr>

                    <th data-field="price" class="col-xs-2">Order</th>
                    <th data-field="price" class="col-xs-2"><i class="glyphicon glyphicon-star"></i>&nbsp;&nbsp;Comment</th>

                </tr>

                </thead>
                {% for order in orders %}
                <tr>

                    <td>
                       <a href="{% url 'job' order.id %}"> {{ order.job }}</a>
                    </td>

                    <td>
                        {{ order.comment }}
                    </td>


                </tr>
                {% endfor %}
            </table>


            {% else %}
            <h2>No cancelled jobs currently</h2>
            {% endif %}
        </div>
</div>
<div class="container navbar-fixed-bottom">
     <hr>
    <div class="row footer">
        &copy steven kyalo 2015
    </div>
</div>
{% endblock content %}

templates/goodlyf/incoming-jobs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12">
           <span class="pull-left h4 text-success">
               <img src="{% static 'images/goodlyf1.png' %}" alt="pic-cleaning" height="33" width="250" />
           </span>
           <a href="{% url 'home' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a>
            {% if user.is_authenticated %}
            <span></span>
            {% else %}
            &nbsp;&nbsp;|&nbsp;&nbsp;
           <a href="{% url 'booking' %}" class="btn btn-primary" title="Book now!">Book online</a>
            {% endif %}

           {% if user.is_authenticated %}
            <span class="text-success pull-right">
               <i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp; {{ user.username|capfirst }}&nbsp;&nbsp;

            <a href="{% url 'logout' %}">logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="pull-right">login</a>

            </span>
            {% endif %}
        </div>
    </div>
</div>
</nav>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-12">
            <h5 class="btn btn-lg pricing-td" style="width: 100%">Incoming Jobs</h5>
        </div>
    </div>
</div>
<br>
 <div class="col-sm-12" id="incoming-jobs">
            <div class="container">
                <div class="row row-centered">
                    <table class="table table-striped table-hover col-xs-12" >
                       <thead>
                        <tr>
                            <th data-field="id" class="col-xs-3">Date Posted</th>
                            <th data-field="name" class="col-xs-3">Service Name</th>
                            <th data-field="price" class="col-xs-3"><i class="glyphicon glyphicon-star"></i>&nbsp;&nbsp;Start Date</th>
                            <th data-field="price" class="col-xs-3">Status</th>
                        </tr>
                        </thead>
                        {% for job in jobs_by_date %}
                        <tr>
                            <td class="col-xs-3">
                                <a href="{% url 'job' job.id %}">{{ job.date_posted }}</a>

                            </td>
                            <td class="col-xs-3">
                                {{ job.service_name }}
                            </td>

                            <td class="col-xs-3">
                               {{ job.date_job_starts }}
                            </td>
                            <td class="col-xs-3">
                                {% if job.state == 0 %}

                                <span class="text-danger"> {{ job.get_state_display }}</span>
                                {% else %}
                                <span class="text-success"> {{ job.get_state_display }}</span>

                                {% endif %}
                                {% if job.assignment == 0 %}

                                <span class="text-danger"> &nbsp;|&nbsp;{{ job.get_assignment_display }}</span>
                                {% else %}
                                <span class="text-success"> &nbsp;|&nbsp;{{ job.get_assignment_display }}</span>
                                {% endif %}

                            </td>


                        </tr>
                        {% endfor %}


                    </table>
                </div>
            </div>

        </div>
        <!--end quotations-->

<hr>
<div class="container navbar-fixed-bottom">
     <hr>
    <div class="row footer">
        &copy steven kyalo 2015
    </div>
</div>
{% endblock content %}

templates/goodlyf/job-feedback.html
{% extends 'base.html' %}
{% block content %}
<div class="container">

    <div class="row">

        {% if job.push_state == 1 %}
        <h4>The job has been pushed to the admin for evaluation</h4>

        {% else %}
        {% if job_feedback_form.errors %}
        <div class="text-danger">Please correct the error{{ job_feedback_form.errors|pluralize }} below.</div>
        {% endif %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="fieldWrapper">
                {{ job_feedback_form.job.errors}}

            </div>
            

            <div class="fieldWrapper">
                {{ job_feedback_form.comment.errors}}
                {{ job_feedback_form.comment.label_tag}}
                    &nbsp;&nbsp;&nbsp;&nbsp;
                    {{ job_feedback_form.comment }}
            </div>
             <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button class="btn btn-info" type="submit" class="btn btn-default">Push</button>
                </div>
            </div>
            
        </form>
        {% endif %}
    </div>
</div>
{% endblock content %}

templates/goodlyf/my-jobs.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
    <div class="row row-centered">
        <div class="col-xs-12">
           <span class="pull-left h4 text-success">
               <img src="{% static 'images/goodlyf1.png' %}" alt="pic-cleaning" height="33" width="250" />
           </span>
           <a href="{% url 'home' %}"><i class="glyphicon glyphicon-home"></i>&nbsp;&nbsp;Home</a>
           {% if user.is_superuser %}
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <a href="{% url 'dashboard' %}">Dashboard</a>
            {% endif %}
            {% if user.is_authenticated %}
            <span></span>
            {% else %}
            &nbsp;&nbsp;|&nbsp;&nbsp;
           <a href="{% url 'booking' %}" class="btn btn-primary" title="Book now!">Book online</a>
            {% endif %}

           {% if user.is_authenticated %}
            <span class="text-success pull-right">
               <i class="glyphicon glyphicon-user"></i>&nbsp;&nbsp; {{ user.username|capfirst }}&nbsp;&nbsp;

            <a href="{% url 'logout' %}">logout</a>
            {% else %}
            <a href="{% url 'login' %}" class="pull-right">login</a>

            </span>
            {% endif %}
        </div>
    </div>
</div>
</nav>
<div class="container">
    <div class="row">
        <div class="col-sm-12 table-responsive">
            <h5 class="btn btn-lg pricing-td" style="width: 100%">My Jobs</h5>
            <h4>Total number of assignments:  &nbsp;&nbsp; <span class="img-circle avg">{{ my_job_count }}</span><span class="pull-right">{{ today }}</span> </h4>
            {% if my_job_list %}
            <table class="table  table-striped table-bordered table-hover no-margin ">
                <thead>
                <tr>
                    <th data-field="id" class="col-xs-2">Job Name</th>
                    <th data-field="price" class="col-xs-2"><i class="glyphicon glyphicon-star"></i>Start Date</th>
                    <th data-field="name" class="col-xs-2">End Date</th>
                    <th class="col-xs-2">Status&nbsp;|&nbsp;Action</th>
                </tr>

                </thead>
                {% for job in my_job_list %}
                <tr>
                    <td>
                        <a href="{% url 'job' job.id %}">{{ job.job.service_name|capfirst }}</a>
                    </td>

                    <td>
                        {{ job.job.date_job_starts }}
                    </td>
                    <td>
                        {{ job.date_job_ends }}
                    </td>
                    <td>
                        {% if job.state == 0 %}
                       <span class="label label label-warning"> {{ job.get_state_display }}</span>
                        {% elif job.state == 1 %}
                        <span class="label label label-info"> {{ job.get_state_display }}</span>
                         {% elif job.state == 2 %}
                        <span class="label label label-success"> {{ job.get_state_display }}</span>
                         {% else %}
                        <span class="label label label-danger"> {{ job.get_state_display }}</span>

                        {% endif %}

                        &nbsp;&nbsp;|&nbsp;&nbsp;
                        <div class="btn-group">
                                <button data-toggle="dropdown" class="btn btn-xs dropdown-toggle" data-original-title="" title="">
                                  Action
                                  <span class="caret">
                                  </span>
                                </button>
                                <ul class="dropdown-menu pull-right">
                                    {% if job.state != 3 %}
                                  <li>
                                    <a class="text-warning" href="{% url 'edit_job' job.id %}">Change</a>
                                  </li>
                                  <li>
                                    <a href="#">Feedback</a>
                                  </li>
                                    {% else %}

                                  <li>
                                    <a href="{% url 'cancelled_job' job.id %}">push to admin</a>
                                  </li>
                                    {% endif  %}
                                </ul>
                        </div>
                    </td>

                </tr>
                {% endfor %}
            </table>


            {% else %}

            <div class="container">
                <div class="row">
                    <div class="jumbotron col-sm-12 login-bg"><span style="color: red ">No jobs assigned to you currently</span></div>
                </div>
            </div>
            {% endif %}
        </div>
        </div>


    </div>
</div>
<br>
<hr>
<div class="container">
	<div class="row">
		<div class="col-sm-12">
			<span class="h4 text-warning">Disclaimer &nbsp; </span>||&nbsp;
			<span class="h5 text-danger">
                Your are required to undertake the responsibilities assigned to you with diligence and integrity.
            </span>
		</div>
	</div>
</div>

<div class="container navbar-fixed-bottom">
     <hr>
    <div class="row footer">
        &copy steven kyalo 2015
    </div>
</div>
<style>
    .avg {
    font-size:30px;
    padding-top: 20px;
    color:#5CB85C;
}
</style>
{% endblock content %}

templates/goodlyf/worker-residence.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-8 col-md-6 col-sm-offset-2 col-md-offset-3">

            <form role='form' id='id_worker_residence_form' method="POST" action="{% url 'worker_residence' worker_obj.id %}" enctype="multipart/form-data">
                <!--display errors-->

                {% if worker_residence_form.errors %}
                <div class="text-danger">Please correct the error{{ worker_residence_form.errors|pluralize }} below.</div>
                {% for field in worker_residence_form.errors %}
                {{ field.error }}
                {% endfor %}
                {% if worker_form.errors %}
                {% for field in worker_form.errors %}
                {{ field.error }}
                {% endfor %}
                {% endif %}
                {% endif %}
                {% csrf_token %}

                <!--form fields -->
                <table>

                    {{ worker_residence_form.as_table }}


                </table>


            <input type="submit" value="Submit">
            </form>
        </div>

    </div>
</div>
{% endblock content %}